# Generated by Django 4.1.7 on 2023-03-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='name',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
